[lint]
select = [
    # https://docs.astral.sh/ruff/rules/#error-e
    # https://github.com/PyCQA/pycodestyle
    "E4",
    "E7",
    "E9",
    # https://docs.astral.sh/ruff/rules/#pyflakes-f
    # https://github.com/PyCQA/pyflakes
    "F",
]
